### ISSUE TITLE
Scaling, Width and Height not working

### ISSUE THREAD

**Issue by Coffee2CodeNL** [sphinx-contrib/plantuml#12]
```rst
..  uml:: server_database.puml
    :width: 25 %
    :align: center
    :caption: Database Structure
```

This does absolutely nothing.
The image is rendered without an link element around it.

It might be best for PNG to always render a link element around it....

**Comment by yuja** [comment]
Which version? It works for me except the align option. There's a hyperlink.

**Comment by iSDP** [comment]
I reckon the latest.

**Comment by jessetan** [comment]
Scale, height and width only work if Pillow (or PIL) is installed, because it is used to get the native image size.
Install using `pip install Pillow` or add to your requirements.txt

**Comment by jmhernandez-circutor** [comment]
@jessetan, I've installed Pillow, but scale, height and width keep not working.

**Comment by compiaffe** [comment]
Installing pillow solved this for me.

**Comment by RedX2501** [comment]
Scale does not seem to be working with svg output. I do have Pillow.

I get no errors or warnings when generating the documents.

The rendered SVGs always have the same size.

I'm using plantuml_output_format svg.

When I fallback to `svg_img` there is no change.

It doesn't matter if I use `:scale: 5 %` or``200 %`. The images all have the same size.

If there's anything else I can do to assist debugging this please let me know.

I'm using version 0.24
