### ISSUE TITLE
Add support for %filename%

### ISSUE THREAD

**Issue by HenrikSolver** [sphinx-contrib/plantuml#2]
Hi.

Thanks for a great extension.
Would it be possible to allow the use the %filename% special variable described here [preprocessing](http://plantuml.com/preprocessing)? I understand that is does not work with this extension since the source is piped thru plantuml. But it might be possible to use the -filename flag when running plantuml.

Thanks

**Comment by yuja** [comment]
I don't think that's doable with `-pipe`, but we could emulate it in Python
as long as the preprocessor is just a `str.replace()`.

https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/preproc/Defines.java#L154

**Comment by yuja** [comment]
Suppose `%filename%` is supported, what do you think should it contain?

a. source document filename
b. output filename
c. output filename without suffix
d. source filename specified in `.. uml:: <filename>` directive or empty

**Comment by yuja** [comment]
fe41f989c00b64e416a719481af8994f67d3dc2d
