### ISSUE TITLE
!include directive no longer works

### ISSUE THREAD

**Issue by weedySeaDragon** [sphinx-contrib/plantuml#20]
The `!include` directive is no longer working.
I now get the error message `Cannot include <the file name>` everywhere I have an `!include` directive.

Seems that it's related to the latest PlantUML changes and how they expect directories to be set/specified.  
The latest PlantUML also broke an IDE plugin with the same error.  Here's that issue in case looking at commit that fixed it is helpful:
 https://github.com/esteinberg/plantuml4idea/issues/193

**Comment by weedySeaDragon** [comment]
FYI - the PlantUML folks have created a BETA version that fixes this.

**Comment by yuja** [comment]
Thanks for the updates!
