### ISSUE TITLE
Question: Handling of syntax errors

### ISSUE THREAD

**Issue by carno** [sphinx-contrib/plantuml#31]
When encountering syntax errors, plantuml prints details to console, generates an image with the error and exits with a non-zero code.

E.g: for
```plantuml
@startuml
note over Bob, Alice, Cat : greetings
Bob -> Alice : hello
Alice -> Cat : hi
@enduml
```
it generates the following image:
![foo](https://user-images.githubusercontent.com/368247/58949193-26584100-878c-11e9-9c92-f8872753fa82.png)

However, due to https://github.com/sphinx-contrib/plantuml/blob/master/sphinxcontrib/plantuml.py#L220 and similar, this plugin does not produce the image, but only logs the error in sphinx generation log.

Would You be willing to change this behaviour (for example by accepting a pull request, that introduces some flag allowing to control this behaviour)?

**Comment by yuja** [comment]
A config knob sounds good to me.
