### ISSUE TITLE
pip install sphinxcontrib-plantuml fails with   error: invalid command 'bdist_wheel'   

### ISSUE THREAD

**Issue by yaccz** [sphinx-contrib/plantuml#33]
solved by `pip install wheel` before installing sphinx-contrib-plantuml

**Comment by yuja** [comment]
Sounds like an environment issue.

**Comment by yaccz** [comment]
Sounds like you are missing wheel in setup.py install_requires but I am not sure.

**Comment by yuja** [comment]
AFAIK, wheel isn't a hard requirement. If pip choose the wheel way, wheel should have
been installed. That's my understanding.

I only uploaded a plain old sdist, which is just a tarball containing sources and metadata.
