### ISSUE TITLE
Feature Request: Add "Out-Of-The-Box" support for C4 diagram modeling

### ISSUE THREAD

**Issue by felipecaputo** [sphinx-contrib/plantuml#34]
Hi, first of all, thank you for this great extension to Sphinx.

I'm using it a lot here and I was think about adopting [C4 Model](https://c4model.com/) in some of my diagrams, and I've found [this extension to PlantUml](https://github.com/RicardoNiepel/C4-PlantUML) but I don't know how to use it with sphinx and your extension since I need a path, and I don't know how it would resolve relative paths (relative to what directory) and I can't have a complete path since my documentation is generated in CI.

It would be possible to support it in you extension?

**Comment by dalito** [comment]
C4 is now included in the plantuml standardlib. Here is an example that works:

```
.. uml::

    !include <C4/C4_Context>
    !define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
    !include FONTAWESOME/users.puml
    Person(user, "C4 fans", "Hello to Sphinx!", $sprite="users")
```

**Comment by felipecaputo** [comment]
Thank you for the feedback
