### ISSUE TITLE
Allow substitutions within diagrams

### ISSUE THREAD

**Issue by gpxricky** [sphinx-contrib/plantuml#37]
Hi there,

at present it is not possible to use RST substitutions within diagrams, e.g.

```
.. uml::

  participant Source
  participant |ShallBeReplaced| as Target

  Source -> Target: call

.. |ShallBeReplaced| replace:: ReplacedTarget
```

Is it possible to add such a functionality to the extension? As far as I know PlantUML uses the pipe symbol for some functionality, but the syntax `|xyz|` is not allowed there. So it could, in theory, work out well.

**Comment by yuja** [comment]
I don't think it's good idea to extend the PlantUML language in a weird way.

Maybe you can instead use the `-DVAR1=value` argument to leverage the
PlantUML's preprocessor. It can't be specified per `.. uml` diagram right now,
but you can embed `-D` in command-line arguments globally.

**Comment by rowanG077** [comment]
I had a prototype up and runnig which used the syntax `_RST[ some rst fragment here]`. Cross ref worked. Somehow I lost that code but I do want to replicate it. I don't think the preprocessor wil work since the same RST fragment can have different output based on the document. Are you totally against something like this because it's one of my most missed features in this plugin @yuja.

**Comment by yuja** [comment]
I think there should be a Sphinx API to capture document-specific reSt substitutions,
and which can be somehow mapped to `-DVAR=value` arguments, by e.g. attaching
to `plantuml` node and translating each subst item by `generate_plantuml_args()`.

> Are you totally against something like this

I'm not against the substitution idea. I don't like the way of extending the PlantUML 
language with reSt syntax. They are incompatible.

**Comment by rowanG077** [comment]
How would the plantuml plugin know what to include into the `-DVAR` arguments? Do we want to start parsing plantuml syntax and find all preprocessor macros? This would also extend plantuml and break other preprocessor macros...

**Comment by yuja** [comment]
No. Substitution rules should be defined in a reSt document. I don't know how they are processed
in Sphinx, but there would be a dictionary of ref to replacement text.

**Comment by rowanG077** [comment]
Refs aren't the only use case for this. RST can perform all kinds of things. Plugins can add their own ref system or text replacements. Simply on focusing on basic links is too simple. I don't think a dictionary of all existing refs in all documents is available anyway.

**Comment by yuja** [comment]
Sorry what is the "basic links"? The original proposal was simple text substitution
by `.. |...| replace:: ...`.

> I don't think a dictionary of all existing refs in all documents is available anyway.

I don't know why we'll need a dict of all existing refs in "all" documents, but yeah, there isn't
a dict containing all substitution definitions for the current document. `document.substitution_defs`
seems close, but it wouldn't include global substitutions for example.

IIUC, the Transformer API handles substitution business, and the transformation applies to
reSt doc tree. It sems the API isn't designed for processing texts of arbitrary syntax. Can
we leverage the Sphinx API to apply substitution on PlantUML document?

**Comment by rowanG077** [comment]
The proposal ask for RST substitutions. That's not simply text substitution, we need to interpret RST and get the resulting node(s). I assume the poster means with the following: `.. |ShallBeReplaced| replace:: ReplacedTarget` That the `replace:: ReplacedTarget` gets interpreted as arbitrary RST not that literally `|ShallBeReplaced|` is replaced with `replace:: ReplacedTarget`.

We could do this using Sphinx API. But I personally don't feel much for having to specify everything twice just so you can put sphinx things in your diagrams.

**Comment by yuja** [comment]
Do you mean translating arbitrary RST nodes (not just texts) to PlantUML equivalents?
That seems not simple and is out of my scope.

Perhaps, the plantuml extension can provide a stub function to be monkey-patched by
the other extension. For example,

```
def preprocess_uml(text):  # to be hooked by other extensions
    return text
p.communicate(preprocess_uml(node['uml']).encode('utf-8'))
```

Does it work for you?

**Comment by gpxricky** [comment]
@yuja That might work. However, I guess this request is too complicated. The original idea was somehow to first preprocess the content of the uml node by Sphinx automatically and then process it with PlantUML. But it seems to be complicated and there might be conflicts between PlantUML syntax and Sphinx syntax.

Therefore I'll close this request.
