### ISSUE TITLE
Undesirable behaviour with width attribute

### ISSUE THREAD

**Issue by bastiedotorg** [sphinx-contrib/plantuml#4]
Hi,

when I set only one of the width/height attributes (in Order to make the diagram fit onto one pdfpage), I encountered an undesirable behaviour:
The image is fixed in both dimensions and thus with a wrong aspect ratio.
I propose the following change: ed47614138f424019ea5f3b73686bc01b1c83521 

This will let the browser scale the image accordingly using css.

Any thoughts?

BR Bastian

**Comment by yuja** [comment]
Can you test the fix? Thanks.
