### ISSUE TITLE
Wrong filename in latexpdf output

### ISSUE THREAD

**Issue by daimrod** [sphinx-contrib/plantuml#42]
The wrong ``tex`` is generated. The file base-name (without the extension) is surrounded by braces.

It generates code like this one:
```latex
\noindent\sphinxincludegraphics{{plantuml-3bbaba0b29484f22faa527b79f77f19d2b140d73}.pdf} % incorrect
```

Instead of code like this one:
```latex
\noindent\sphinxincludegraphics{plantuml-3bbaba0b29484f22faa527b79f77f19d2b140d73.pdf} % correct
```

No issue with the html output format. Thanks for your plugin!

**Comment by yuja** [comment]
Looks like that's expected output.
https://github.com/sphinx-doc/sphinx/commit/2ee03a272941da480e933478c7b1ae3153158bca
