### ISSUE TITLE
Fails with the PlantUML 1.2020.15

### ISSUE THREAD

**Issue by rizickus** [sphinx-contrib/plantuml#45]
Generates "very descriptive" error messages :) like this:

WARNING: error while running plantuml
b''

Diagrams are correct, worked fine with older versions.
Version in pip shows 0.18, Sphinx v3.1.2, Win 10 OS.

**Comment by MikeSmithEU** [comment]
Works for me on that version (on Mac OS Catalina and with an old sphinx version):

Output of `plantuml -version`:

```
PlantUML version 1.2020.15 (Sun Jun 28 13:39:45 CEST 2020)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: UTF-8
Language: en
Country: BE

PLANTUML_LIMIT_SIZE: 4096

Dot version: dot - graphviz version 2.44.1 (20200629.0846)
Installation seems OK. File generation OK
```

Python 3.8.5, pip 20.2.1, sphinx 1.8.3

**Comment by rizickus** [comment]
Works as expected with the latest versions. Could be related with OpenJDK updates. Closing.
