### ISSUE TITLE
No support with paths with whitespaces

### ISSUE THREAD

**Issue by RedX2501** [sphinx-contrib/plantuml#66]
It seems that unlike the `.. image::` directive the `.. uml::` directive does not support spaces in the path.

The exact error is:

```
Error in "uml" directive:
maximum 1 argument(s) allowed, 4 supplied.

.. uml:: images/L3\ -\ Component\ Diagram.puml
   :caption: The caption
```

Is there a workaround for this (without removing the spaces from the path).

Example:

```rst
.. uml:: images/L3\ -\ Component\ Diagram.puml
```

Version: sphinxcontrib-plantuml        0.23

**Comment by RedX2501** [comment]
Thank you for the quick fix.

When can we expect a release?

**Comment by yuja** [comment]
> When can we expect a release?

Done.
