### ISSUE TITLE
Offer an svg image option

### ISSUE THREAD

**Issue by jsamr** [sphinx-contrib/plantuml#7]
`svg` option is great, but there is some width caveats when wider than its container, see bellow screenshots. One way to bypass this issue is to include svg as an image instead of embedded object. So perhaps you could provide `svg-image` and `svg-embedded` options ?

**example with svg**
![image](https://user-images.githubusercontent.com/3646758/35698147-3fcb252a-075a-11e8-9151-609390615ed2.png)

**example with png**
![image](https://user-images.githubusercontent.com/3646758/35698094-1b31e2bc-075a-11e8-8c24-6c0e255de24e.png)

**Comment by yuja** [comment]
Seems fine. Patches are welcome.

**Comment by iSDP** [comment]
Easily Solvable!

add this to `config.py`:
```python
def setup(app):
    app.add_stylesheet('custom.css')
```
and this to `_static/custom.css`:
```css
p.plantuml > object {
    max-width: 100%;
}
```

**Comment by jessetan** [comment]
If yuo're providing custom CSS, you also need a `height: auto !important;` to make sure it uniformly scales. And yes, you need that ugly `!important` to override the inline style set on the object element

**Comment by melvinvermeeren** [comment]
See PR #17

**Comment by jsamr** [comment]
@melvinvermeeren great work, thank you so much !
