### ISSUE TITLE
SVG output width and height for HTML output

### ISSUE THREAD

**Issue by ndee02** [sphinx-contrib/plantuml#71]
Currently, the `:width:` and `:height:` properties are ignored for SVG outputs. This is a bit annoying, as for PNG, the output image is properly resized if you specify those properties. In addition, SVG offers much better options to define the display size (as the name suggests, it is a scalable vector graphic): percentages for width are a feasible option.

I had a look at the code, and for SVG, it currently just copies the calculated width and height in pixels from the SVG and puts it to the `<object>` tag.
I suggest to substitute width and height with the properties given to the directive instead. `:width: 100%` would work nicely for SVGs and HTML output.
An additional consideration would be to add also a `:max-width:` property.

It seems it would at least partially address other user's findings:
* general discussion about scaling and display size: https://github.com/sphinx-contrib/plantuml/issues/15
* findings about SVG and the `:scale:` option not working https://github.com/sphinx-contrib/plantuml/issues/12#issuecomment-1175215100_
* similar finding as here, proposed solution was to just enforce max-width with css style sheet in HTML theme: https://github.com/sphinx-contrib/plantuml/issues/7

**Comment by yuja** [comment]
Makes sense. Apparently, this is just not implemented yet after 210a47fc9da5 and 64a571f1ed28.

**Comment by ndee02** [comment]
resolved in #72
