### ISSUE TITLE
Offer an option to disable the UML directives

### ISSUE THREAD

**Issue by bavovanachte** [sphinx-contrib/plantuml#8]
Hi,

In our documentation, I am looking to see how documentation builds can be sped up. Often we just want to see if the docs build without warnings, before committing the changes. In this case, it's not needed to build all the plantuml diagrams in our documentation.

So in that use case, it would be nice if we could temporarily disable the building of plantuml diagrams (without it generating warnings because of this) as this takes a considerable amount of time. Then, the CI would do the full build (with diagrams) and publish the document.

**Comment by SteinHeselmans** [comment]
Proposal for implementation:

Add a configuration variable (e.g. `plantuml_bypass`) which is default `False`, but can be set to `True` in `conf.py`. When this config is True, the plugin doesn't render an image, but replaces the node with a message (e.g. an admonition node with note: plantuml plugin disabled through plantuml_bypass config variable).

**Comment by yuja** [comment]
Perhaps `plantuml_output_format` could be extended to support
`none` or `raw` (to embed source text.)

Patches are welcome.

**Comment by SteinHeselmans** [comment]
tested in 0.10 using
`plantuml_output_format = 'none' `

ok: no plantuml rendering, so build is faster

but: a warning for every uml directive in terminal and no content (e.g. warning node) in generated html

**Comment by yuja** [comment]
Use the current master branch, not the released one.

**Comment by SteinHeselmans** [comment]
aha, silly me, using the wrong version :1st_place_medal: 

ok: no warning in terminal :+1: 

( small improvement could be to render a warning admonition in generated html )
